#############################################################
##
##  PHP view of Jig workspace
##
#############################################################

class: Zig\View\Document\Workspace
title: "Carthistoire"

#############################################################
## HEADER

# Geoportal API key :
#   ign.cartapatate.net : 1272922719054764550
#   dev.ign.cartapatate.net : 150484252516911842
#   histoire.cartapatate.net : 499880235241209162
#   demo.histoire.cartapatate.net : 7910055355878502507
#   test.histoire.cartapatate.net : 6472869456986670315
#   dev.histoire.cartapatate.net : 6651562387375405070
#

packageScripts: false
packageStyles: false

scripts:
  dojo: /x/dojo/dojo.js
  openlayers: /js/openlayers/build/OpenLayers.js
  ign: http://api.ign.fr/geoportail/api?v=1.1-e&amp;key=499880235241209162&amp;instance=VISU
  workspace: /x/workspace_default.js?z
  start: /js/start.js

scriptAffectations:
  window\.workspaceKey: home
  #window\.workspaceData:

css:
  #ol: /js/openlayers/themes/default/style.css
  #app: /js/ign/css/application.css
  app: /x/histoire/css/application.css
  #tundra: /x/dijit/themes/tundra/tundra.css
  #tundra: /js/dijit/themes/tundra/tundra.css

#############################################################
## BODY

bodyAttributes:
  class: patate tundra


bodyInnerHtml:
  app:
    tag: div
    attributes:
      id: app
    content: ""
  wait:
    tag: div
    attributes:
      id: wait
    content:
      sub:
        tag: div
        content: "Chargement de l'application..."

widgets:
  root:
    _class: jig.layout.RootPane
    state:
      children:
        - mainContainer
      toaster:
        positionDirection: tl-down
        #positionDirection: br-up
      #  # "br-up", "br-left", "bl-up", "bl-right", "tr-down", "tr-left", "tl-down", "tl-right"
  mainContainer:
    _class: jig.layout.BorderContainer
    state:
      design: sidebar
      children:
        - map
        #- about
        #- layers
        - sideContainer
      paneSize: 250
  map:
    #_class: ploomap.map.GeoportalMinimum
    _class: ploomap.map.Geoportal
    #_class: ploomap.map.Classical
    state:
      layersDefsClass: histoire.layerDef.Application
      layers:
        - { name: GEOGRAPHICALGRIDSYSTEMS.MAPS, opacity: 0.5 }
        - revolution_francaise
        - worldwar2
      center:
        x: 179800
        y: 5438000
        zoom: 5
        #zoom: 13
      buttons:
        location: false
        tools: false
      controls:
        #- OpenLayers.Control.KeyboardDefaults
        #- { class: OpenLayers.Control.Navigation, options: { mouseWheelOptions: { interval: 100 } } }
        #- OpenLayers.Control.MousePosition
        #- OpenLayers.Control.PanZoomBar
        - ploomap.OpenLayers.Control.SexyZoomBar
        #- Geoportal.Control.SearchToolbar
        #- Geoportal.Control.ToolBox
        #- Geoportal.Control.AddImageLayer
        #- Geoportal.Control.AddVectorLayer
        #- Geoportal.Control.BasicLayerToolbar
        #- Geoportal.Control.EditingToolbar
        #- Geoportal.Control.LayerToolbar
        #- Geoportal.Control.LocationUtilityService.Geocode
        #-
        #- Geoportal.Control.
        #- Geoportal.Control.
        - { class: ploomap.OpenLayers.Control.ScaleLine, options: { maxWidth: 150, geodesic: true } }
        #- ploomap.OpenLayers.Control.TileLoadSpinner
  sideContainer:
    _class: jig.layout.BorderContainer
    state:
      design: headline
      children:
        - about
        - layers
        #- overviewMap
        #- macroEditor
        #- sideContainer2
      paneSize: 400
  macroEditor:
    _class: jig.macro.Editor
  sideContainer2:
    _class: jig.layout.BorderContainer
    state:
      design: headline
      children:
        - overviewMap
        - about
      paneSize: 150
  layers:
    _class: ploomap.tool.Layers
    state:
      mapWidget: map
      appearTarget: bottom
  overviewMap:
    _class: ploomap.tool.OverviewMap
    state:
      mapWidget: map
      copyLayer: GEOGRAPHICALGRIDSYSTEMS.MAPS #_FXX_territory_
  about:
    _class: histoire.info.About

settings:
  layerManager:
    layerLibraryClass: histoire.layerLibrary.Application
  layers:
    #- ign
    #- geol
    #- igc_paris
    #- igc_versailles
    #- osm
    #- cassini
    #- velib
    #- communes_fr_geoportal
    - ADDRESSES.CROSSINGS
    - ADMINISTRATIVEUNITS.BOUNDARIES
    - BUILDINGS.BUILDINGS
    - CADASTRALPARCELS.PARCELS
    - ELEVATION.SLOPS
    - GEOGRAPHICALGRIDSYSTEMS.MAPS
    - HYDROGRAPHY.HYDROGRAPHY
    - ORTHOIMAGERY.ORTHOPHOTOS
    - ELEVATION.LEVEL0
    - TOPONYMS.ALL
    - TRANSPORTNETWORKS.RAILWAYS
    - TRANSPORTNETWORKS.ROADS
    - TRANSPORTNETWORKS.RUNWAYS
    - UTILITYANDGOVERNMENTALSERVICES.ALL
    - revolution_francaise
    - worldwar2
    #- test

  mapTools:
    tools:
      - ploomap.tool.Magnifier
      - ploomap.tool.OverviewMap
      - ploomap.tool.Measure
      - ploomap.tool.Export
      - ploomap.tool.StreetView
      - ploomap.tool.Itineraries
      - jig.tool.UserFeedback
      - histoire.info.About



  historicalFacts:
    attributes:
      name:
        label: Nom
        type: string
      title:
        label: Titre
        type: string
      date:
        label: Date
        type: date
      story:
        label: Histoire
        type: textarea
      characters:
        label: Personnages
        type: textarea
      url:
        label: URL
        type: string
      image_url:
        label: URL image
        type: string

  worldWar2:
    attributes:
      name:
        label: Nom
        type: string
      title:
        label: Titre
        type: string
      date:
        label: Date
        type: date
      story:
        label: Histoire
        type: textarea
      actors:
        label: Personnages
        type: textarea
      image:
        label: Source
        type: string
      source:
        label: Image
        type: string
