#############################################################
##
##  PHP view of Jig workspace
##
#############################################################

class: Zig\View\Document\Workspace
title: Catapatate 2 preview

#############################################################
## HEADER

# GMap key is
#   for http://okamap.dev.lapatate.org :
#     ABQIAAAAbLRoNMqR4Pen1V9KJHqHFxTJc1TUOWfJSEQIrIow9EO1M6xJcxSGLig3Jv_uQH7Ib8J_8p3ymhPI0w
#   for dev.hurepoix.cartapatate.eu :
#     ABQIAAAAbLRoNMqR4Pen1V9KJHqHFxQIEZYXS1xL9TiWNpXW1Rj76Uuj9RTtctqibZiCwemgGivc_9UXn56X9w

packageScripts: false
packageStyles: false

scripts:
  - /x/dojo/dojo.js
  #- /js/dojo/dojo.js
  # cartapatate.net : ABQIAAAAbLRoNMqR4Pen1V9KJHqHFxQA367lAHlkjABbUcAop0DGCpL_0RR1Fbs6U1WlvDJ0jWdsrgcAgGKukA
  # hurepoix.cartapatate.net : ABQIAAAAbLRoNMqR4Pen1V9KJHqHFxR8LCrIApkag7e2Ys8b_uzh20QCThSoLziwEEBX_zMriMcJhAtf5ZeRzQ
  # dev.hurepoix.cartapatate.net : ABQIAAAAbLRoNMqR4Pen1V9KJHqHFxQIEZYXS1xL9TiWNpXW1Rj76Uuj9RTtctqibZiCwemgGivc_9UXn56X9w
  #- http://maps.google.com/maps/api/js?v=3&sensor=false
  - http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAAbLRoNMqR4Pen1V9KJHqHFxQA367lAHlkjABbUcAop0DGCpL_0RR1Fbs6U1WlvDJ0jWdsrgcAgGKukA
  - /js/proj4js/lib/proj4js-compressed.js
  #- http://openlayers.org/api/OpenLayers.js
  - /js/openlayers/build/OpenLayers.js
  - /x/workspace_default.js
  - /js/start.js

scriptAffectations:
  window\.workspaceKey: home
  #window\.workspaceData:

css:
  - /js/openlayers/themes/default/style.css
  - /js/catapatate/css/application.css
  #- /x/dijit/themes/tundra/tundra.css
  #- /js/dijit/themes/tundra/tundra.css
  - /x/jig/css/jig.css
  #- /js/jig/css/jig.css


#############################################################
## BODY

bodyAttributes:
  class: patate tundra


bodyInnerHtml:
  app:
    tag: div
    attributes:
      id: app
    content: ""
  wait:
    tag: div
    attributes:
      id: wait
    content:
      sub:
        tag: div
        content: "Chargement de l'application..."

widgets:
  root:
    _class: jig.layout.RootPane
    state:
      children:
        - mainContainer
      toaster:
        positionDirection: bl-up
        # "br-up", "br-left", "bl-up", "bl-right", "tr-down", "tr-left", "tl-down", "tl-right"
  mainContainer:
    _class: jig.layout.BorderContainer
    state:
      design: sidebar
      children:
        - map
        - sideContainer
      paneSize: 250
  map:
    _class: ploomap.map.Classical
    state:
      __center:         # Etampes
        x: 239878
        y: 6179274
        zoom: 14
      center:      # Paris
        x: 260535
        y: 6249816
        zoom: 13
      controls:
        #- OpenLayers.Control.KeyboardDefaults
        - { class: OpenLayers.Control.Navigation, options: { mouseWheelOptions: { interval: 100 } } }
        - OpenLayers.Control.PanZoomBar
        - { class: OpenLayers.Control.ScaleLine, options: { maxWidth: 150, geodesic: true } }
        - ploomap.OpenLayers.Control.TileLoadSpinner
  sideContainer:
    _class: jig.layout.BorderContainer
    state:
      design: headline
      children:
        - layers
        - overviewMap
        #- about #sideContainer2
      paneSize: 400
  sideContainer2:
    _class: jig.layout.BorderContainer
    state:
      design: headline
      children:
        - overviewMap
        - about
      paneSize: 150
  layers:
    _class: ploomap.tool.Layers
    state:
      mapWidget: map
      appearTarget: bottom
  overviewMap:
    _class: ploomap.tool.OverviewMap
    state:
      mapWidget: map
  about:
    _class: catapatate.info.About

settings:
  layers:
    - ign
    - geol
    - igc_paris
    - igc_versailles
    - osm
    - cassini
    - velib
    - communes_fr
    - elements
    - bss
    #- test
  mapTools:
    tools:
      - ploomap.tool.Magnifier
      - ploomap.tool.OverviewMap
      - ploomap.tool.Measure
      - ploomap.tool.Export
      - ploomap.tool.StreetView
      - ploomap.tool.Itineraries
      - jig.tool.UserFeedback
      - catapatate.info.About




  elementTypes:
    acces:
      attributes:
        coords:
          label: Coordonnées
          type: coords
          save: false
        nom:
          label: Nom
          type: name
        emplacement:
          label: Emplacement
          type: string
          default:
        usage:
          label: "Usage"
          type: select
          default: inconnu
          options:
            ps: "Puits de service"
            peau: "Puits à eau"
            pe: "Puits d'extraction"
            comm: "Puits de communication"
            entree: "Entrée"
            artesien: "Puits artésien"
            autre: "Autre"
            inconnu: "Inconnu"
        acces:
          label: "Accès"
          type: select
          default: inconnu
          options:
            rd_soleil: "Plaque ronde, soleil"
            rd_tortue: "Plaque ronde, tortue"
            rd_egouts: "Plaque ronde, type égouts"
            rd_legere: "Plaque ronde, très légère"
            rd_carree: "Plaque ronde IDC"
            rd_autre: "Plaque ronde, autre type"
            rt_ptt: "Plaque rectangulaire, type PTT"
            rt_triangle: "Plaque rectangulaire, ouverture en triangles"
            rt_complexe: "Plaque rectangulaire, mécanisme complexe"
            rt_autre: "Plaque rectangulaire, autre type"
            plaque: "Autre type de plaque"
            porte: "Porte métallique"
            trou: "Trou percé (chatière)"
            plaquesmetal: "Plaques de métal"
            rien: "Trou sans couverture"
            cavage: "Cavage"
            treuil: "Ouverture sur treuil"
            autre: "Autre type d'accès"
            inexistant: Inexistant
            inconnu: "Inconnu"
        acces_detaille:
          label: "Accès détaillé"
          type: select
          default: non_precise
          options:
            non_precise: Non précisé
            carriere_idc: Carrières - IDC
            carriere_soleil: Carrières - soleil
            carriere_idc_soleil: Carrières - IDC+soleil
            carriere_double_battants_triangles: Carrières - double-battants - triangles
            carriere_double_battants_beton: Carrières - double-battants - béton
            carriere_double_battants_metal: Carrières - double-battants - métal
            carriere_mutiples_battants_3: Carrières - multiples-battants - 3
            carriere_mutiples_battants_4: Carrières - multiples-battants - 4
            carriere_mutiples_battants_5: Carrières - multiples-battants - 5
            carriere_mutiples_battants_6+: Carrières - multiples-battants - 6+
            egout_quadrillage_grave: Égout - quadrillage gravé
            egout_sans_marquage: Égout - sans marquage
            egout_vanne: "Égout - avec vanne d'eau"
            egout_patte_doie: "Égout - petite avec motif patte d'oie"
            egout_legere_languette: Égout - légère à languette
            egout_lourde_languette: Égout - lourde à languette
            ratp_grille: RATP - grille
            ratp_claire_voie: RATP - claire voie
            ratp_claire_voie_grille: RATP - claire-voie entourée de grille
            edf: EDF
            edf_cpde: EDF - CPDE
            edf_cpde_mht: EDF - CPDE-MHT
            edf_verrins: EDF - à verrins
            ptt_rdlr: PTT - RDLR
            ptt_barat: PTT - BARAT
            ptt_sebel: PTT - SEBEL
            ptt_trefle: PTT - sans marquage, serrure trèfle
            ptt_accroche: "PTT - sans marquage, trou d'accroche"
        descente:
          label: Descente
          type: select
          default:
          options:
            pt: "Puits"
            pt_ech: "Puits à échelons"
            pt_sech: "Puits sans échelons"
            pt_echll: "Puits à échelle"
            esc: "Escalier en colimaçon"
            esc_dr: "Escalier droit"
            pente_douce: "Pente douce"
            chatiere: "Chatière"
            simple: "Simple"
            aucune: "Aucune"
            autre: "Autre"
            inconnu: "Inconnu"
        etat_general:
          label: État général
          type: select
          default: inconnu
          options:
            inconnu: Inconnu
            condamne: Condamné
            ferme: Fermé
            ouvert: Ouvert
        etat:
          label: État
          type: select
          default: inconnu
          options:
            ouvert: Ouvert
            difficile: Difficile
            soudure: Soudé
            clef: "Fermé à clef"
            beton: Bétonné
            recouvement: Recouvert
            comblement: Comblé
            autre: Autre
            inconnu: Inconnu
        remarques:
          label: Observations
          type: textarea
          default:

    lieu:
      attributes:
        nom:
          label: Nom
          type: name
          default:
        categorie:
          label: Type
          type: select
          options:
            salle: "Salle"
            squat: "Squat"
            reseau: "Réseau"
            chatiere: "Chatière"
            fontis: "Fontis"
            puits_a_eau_carriere: "Puits à eau (en carrière)"
            puits_a_eau_surface: "Puits à eau (en surface)"
            curiosite: "Curiosité"
            abri: "Abri de défense passive"
            lieudit: "Lieu-dit"
            ossuaire: "Ossuaire"
            cabinet: "Cabinet minéralogique"
            champignonniere: "Champignonnière"
            brasserie: "Brasserie"
            cave_carriere: "Cave-carrière"
            batiment_surface: "Bâtiment en surface"
            crypte: "Crypte"
            grotte: Grotte
            autre: "Autre"
        taille:
          label: Taille
          type: string
          default:
        remarques:
          label: Observations
          type: textarea
          default:

    galerie:
      attributes:
        nom:
          label: Nom
          type: name
          default:
        remarques:
          label: Observations
          type: textarea
          default:

    grandaxe:
      attributes:
        nom:
          label: Nom
          type: name
          default:
        remarques:
          label: Observations
          type: textarea
          default:

    egout:
      attributes:
        nom:
          label: Nom
          type: name
          default:
        usage:
          label: Type
          type: select
          default: inconnu
          options:
            collecteur: "Égout collecteur"
            orage: "Déversoir d'orage"
            simple: "Galerie d'égouts simple"
            acqueduc: Aqueduc
            riviere_souterraines: Rivière souterraine
            autre: Autre
            inconnu: Inconnu
        remarques:
          label: Observations
          type: textarea
          default:

    galerie_technique:
      attributes:
        nom:
          label: Nom
          type: name
          default:
        usage:
          label: Type
          type: select
          default: inconnu
          options:
            ptt: PTT
            edf: EDF
            ratp: RATP
            autre: Autre
            inconnu: Inconnu
        remarques:
          label: Observations
          type: textarea
          default:

    delimitation:
      attributes:
        nom:
          label: Nom
          type: name
          default:
        objet:
          label: Objet
          type: select
          default: inconnu
          options:
            enceinte: Enceinte
            admini: Délimitation administrative
            geol: Délimitation géologique
            autre: Autre délimitation
        remarques:
          label: Remarques
          type: textarea
          default:

    secteur:
      attributes:
        nom:
          label: Nom
          type: name
          default:
        remarques:
          label: Observations
          type: textarea
          default:

    reseau:
      attributes:
        nom:
          label: Nom
          type: name
          default:
        type:
          label: Type
          type: select
          default: non_precise
          options:
            non_precise: Non précisé
            carriere: Carrière
            mine: Mine
        exploitation:
          label: Exploitation
          type: select
          default: inconnu
          options:
            calcaire: Calcaire
            craie: Craie
            gypse: Gypse
            marne: Marne
            sable: Sable
            argile: Argile
            lignite: Lignite
            houille: Houille
            argent: Argent
            diamant: Diamant
            or: Or
            autre: Autre
            inconnu: Inconnu
        remarques:
          label: Observations
          type: textarea
          default:
