imports:
  - { resource: doctrine.yml }
  - { resource: zig.install.yml }

parameters:
    kernel.include_core_classes: false

kernel.config:
  charset: UTF-8
  error_handler_level: null

web.templating:
  escaping:       htmlspecialchars
  assets_version: SomeVersionScheme

web.config:
  router: { resource: "%kernel.root_dir%/config/routing.yml" }

web.templating: ~

zig.registry: ~

zig.api: ~

#  directory: config/registry

swift.mailer:
  transport: smtp #gmail
  host: localhost #smtp.dedibox.fr
  #username:
  #password:

