doctrine.dbal:
  default_connection: default
  connections:
    default:
      driver: PDOPgSql  # PDOSqlite, PDOMySql, PDOMsSql, PDOOracle, PDOPgSql, OCI8
      dbname: cartapatate_hurepoix
      user: cartapatate
      password: pFWxLvY58
      a:
        a1: sde
        a2: zedfzre

doctrine.orm:
  default_entity_manager: default
  metadata_driver: annotation           # xml, yml, annotation
  cache_driver: apc                     # array, apc, memcache, xcache
  entity_managers:
    default:
      connection: default
