
title: "Carthistoire [DEV]"

#scripts.openlayers: /js/openlayers/lib/OpenLayers.js

#scripts.dojo: /js/dojo/dojo.js
scripts.workspace: null
#scripts.workspace: /x/workspace_default.js.uncompressed.js?z

scripts.ign: http://api.ign.fr/geoportail/api?v=1.1-e&amp;key=6651562387375405070&amp;instance=VISU
css.app: /js/histoire/css/application.css

bodyAttributes.class: patate tundra dev
