#############################################################
##
##  PHP view of Jig workspace
##
#############################################################

class: Geonef\Zig\View\Document\Workspace
title: Carthistoire

#############################################################
## HEADER

# Geoportal API key :
#   ign.cartapatate.net : 1272922719054764550
#   dev.ign.cartapatate.net : 150484252516911842
#   histoire.cartapatate.net : 499880235241209162
#   demo.histoire.cartapatate.net : 7910055355878502507
#   test.histoire.cartapatate.net : 6472869456986670315
#   dev.histoire.cartapatate.net : 6651562387375405070
#   dev-okapi.carthistoire.geonef.fr : 4784174920139738391 (exp 24/05/2012)
#
packageScripts: false
packageStyles: false

scripts:
  dojo: /x/dojo/dojo.js
  checkBrowser: >-
    if (!dojo.isFF && !dojo.isChrome) {
      alert("Vous utilisez un navigateur autre que Firefox ou Chrome,\n" +
            "sur lequel l'application n'a pas été testée.\n\n" +
            "Il est donc probable qu'elle fonctionne mal ou pas du tout.");
    }
  # openlayers: /js/openlayers/build/OpenLayers.js
  ign: http://api.ign.fr/geoportail/api?v=1.1-e&amp;key=499880235241209162&amp;instance=VISU
  application: /x/application.js
  # workspace: /x/workspace_default.js?z
  # start: /js/start.js

scriptAffectations:
  window\.workspaceKey: home
  window\.workspaceObjDeps: []
  #window\.workspaceData:

css:
  app: /x/geonef/histoire/style/application.css

#############################################################
## BODY

bodyAttributes:
  class: patate tundra


bodyInnerHtml:
  app:
    tag: div
    attributes:
      id: app
    content: ""
  wait:
    tag: div
    attributes:
      id: wait
    content:
      sub:
        tag: div
        content: "Chargement de l'application..."

widgets:
  root:
    _class: geonef.jig.layout.RootPane
    state:
      children:
        - mainContainer
      toaster:
        positionDirection: tl-down
        #positionDirection: br-up
      #  # "br-up", "br-left", "bl-up", "bl-right", "tr-down", "tr-left", "tl-down", "tl-right"
  mainContainer:
    _class: geonef.jig.layout.BorderContainer
    state:
      design: sidebar
      children:
        - map
        #- about
        #- layers
        - sideContainer
      paneSize: 280
  map:
    #_class: geonef.ploomap.map.GeoportalMinimum
    _class: geonef.ploomap.map.Geoportal
    #_class: geonef.ploomap.map.Classical
    state:
      layersDefsClass: geonef.histoire.layerDef.Application
      layers:
        - { name: GEOGRAPHICALGRIDSYSTEMS.MAPS, opacity: 0.5 }
        - revolution_francaise
        - worldwar2
      center:
        x: 179800
        y: 5438000
        zoom: 5
        #zoom: 13
      buttons:
        location: false
        tools: false
      controls:
        #- OpenLayers.Control.KeyboardDefaults
        #- { class: OpenLayers.Control.Navigation, options: { mouseWheelOptions: { interval: 100 } } }
        #- OpenLayers.Control.MousePosition
        #- OpenLayers.Control.PanZoomBar
        - geonef.ploomap.OpenLayers.Control.SexyZoomBar
        #- Geoportal.Control.SearchToolbar
        #- Geoportal.Control.ToolBox
        #- Geoportal.Control.AddImageLayer
        #- Geoportal.Control.AddVectorLayer
        #- Geoportal.Control.BasicLayerToolbar
        #- Geoportal.Control.EditingToolbar
        #- Geoportal.Control.LayerToolbar
        #- Geoportal.Control.LocationUtilityService.Geocode
        #-
        #- Geoportal.Control.
        #- Geoportal.Control.
        - { class: geonef.ploomap.OpenLayers.Control.ScaleLine, options: { maxWidth: 150, geodesic: true } }
        #- geonef.ploomap.OpenLayers.Control.TileLoadSpinner
  sideContainer:
    _class: geonef.jig.layout.BorderContainer
    state:
      design: headline
      children:
        - about
        - layers
        #- overviewMap
        #- macroEditor
        #- sideContainer2
      paneSize: 200
  macroEditor:
    _class: geonef.jig.macro.Editor
  sideContainer2:
    _class: geonef.jig.layout.BorderContainer
    state:
      design: headline
      children:
        - overviewMap
        - about
      paneSize: 150
  layers:
    _class: geonef.ploomap.tool.Layers
    state:
      mapWidget: map
      appearTarget: bottom
  overviewMap:
    _class: geonef.ploomap.tool.OverviewMap
    state:
      mapWidget: map
      copyLayer: GEOGRAPHICALGRIDSYSTEMS.MAPS #_FXX_territory_
  about:
    _class: geonef.histoire.info.About

settings:
  layerManager:
    layerLibraryClass: geonef.histoire.layerLibrary.Application
  layers:
    #- ign
    #- geol
    #- igc_paris
    #- igc_versailles
    #- osm
    #- cassini
    #- velib
    #- communes_fr_geoportal
    - ADDRESSES.CROSSINGS
    - ADMINISTRATIVEUNITS.BOUNDARIES
    - BUILDINGS.BUILDINGS
    - CADASTRALPARCELS.PARCELS
    - ELEVATION.SLOPS
    - GEOGRAPHICALGRIDSYSTEMS.MAPS
    - HYDROGRAPHY.HYDROGRAPHY
    - ORTHOIMAGERY.ORTHOPHOTOS
    - ELEVATION.LEVEL0
    - TOPONYMS.ALL
    - TRANSPORTNETWORKS.RAILWAYS
    - TRANSPORTNETWORKS.ROADS
    - TRANSPORTNETWORKS.RUNWAYS
    - UTILITYANDGOVERNMENTALSERVICES.ALL
    - revolution_francaise
    - worldwar2
    #- test

  mapTools:
    tools:
      - geonef.ploomap.tool.Magnifier
      - geonef.ploomap.tool.OverviewMap
      - geonef.ploomap.tool.Measure
      - geonef.ploomap.tool.Export
      - geonef.ploomap.tool.StreetView
      - geonef.ploomap.tool.Itineraries
      - geonef.jig.tool.UserFeedback
      - geonef.histoire.info.About



  historicalFacts:
    attributes:
      name:
        label: Nom
        type: string
      title:
        label: Titre
        type: string
      date:
        label: Date
        type: date
      story:
        label: Histoire
        type: textarea
      characters:
        label: Personnages
        type: textarea
      url:
        label: URL
        type: string
      image_url:
        label: URL image
        type: string

  worldWar2:
    attributes:
      name:
        label: Nom
        type: string
      title:
        label: Titre
        type: string
      type:
        label: Type
        type: select
        options:
          mouvement: Mouvement de troupes
          affrontement: Affrontement
          camp: Camp de concentration
          communication: Communication
      date:
        label: Date
        type: date
      story:
        label: Histoire
        type: textarea
      actors:
        label: Personnages
        type: textarea
      source:
        label: Source
        type: string
      image:
        label: Image
        type: string
