#catapatate:
#  resource: CatapatateBundle/Resources/config/routing.yml
zig:
  resource: ZigBundle/Resources/config/routing.yml
ploomap:
  resource: PloomapBundle/Resources/config/routing.yml

homepage:
  pattern: /
  defaults: { _controller: "ZigBundle:ViewClass:render", path: "views.workspace" }

geoportal:
  pattern: /geoportal
  defaults: { _controller: "ZigBundle:ViewClass:render", path: "views.geoportal" }

