
title: "Carthistoire [DEV-OKAPI]"

# uncomment this to get non-schrinked dojo
#scripts.dojo: /js/dojo/dojo.js
scripts.ign: http://api.ign.fr/geoportail/api?v=1.1-e&amp;key=6651562387375405070&amp;instance=VISU
scripts.application: null
scripts.start1: /lib/cartapatate/start.js
scripts.start2: /lib/cartapatate/start/loadWorkspace.js
#scripts.openLayers: /js/openlayers/lib/OpenLayers.js

css.app: /lib/geonef/histoire/style/application.css

scriptAffectations.window\.devMode: true

bodyAttributes.class: patate tundra dev

